### ISSUE TITLE
Processing speed: Improving workflow for the user?

### ISSUE THREAD

**Issue by FrithjofVollmer** [cannam/expressive-means#23]
Dear Chris, 

one interesting thing I found in Matthias' pYin: the plugins seems to provide its data 'right on the way', that is, I can see (and work with) the pitch curve even the plugin is still processing. Is there a mode in SV, at least for low-level features, that allows plugins to provide data 'real-time' (i.e., returning results right when the analysis passed the respective hop)? 

If yes (and if it's not too time-consuming to install), this probably would be a great thing for our plugins: For an audio of 4 1/2 minutes in 44,1 / 16, they currently take 54 seconds for processing on my computer (which is operating on an M1 chip, so colleagues with older processors may wait even minutes). This probably sounds not particularly dramatic, but I becomes a real burden if various parameter settings have to be tested (i.e., 6–7 turns of processing). 

Thanks Chris! (On everything else, you'll receive an email soon!)

**Comment by FrithjofVollmer** [comment]
Assuming that this is something which is in the domain of SV itself (considering the architecture of Vamp plugins...?) – issue closed for now.

**Comment by cannam** [comment]
This is actually not an unreasonable thing to consider - it is mostly within the plugin's domain rather than SV's. Plugins can return values as they receive input, and/or do some calculation at the end and return the values then.

The problem is that not all methods can be written to return values as they go. Those that can be, i.e. that have limited lookahead and don't require the whole input in advance, are typically known as "causal" methods. It's not always clear when you start to work on a method whether it will turn out to be implementable that way or not, and often it's easier to implement a method with access to the whole input even if it isn't strictly necessary.

In the case of pYin, the method as published is actually non-causal because it performs a full Viterbi decode across the candidate pitch track before returning anything. However the pYin plugin has an option for "fixed-lag" decoding which makes it able to return decoded output as it goes - this is on by default, which is why you observed that pYin worked that way, but it only happens because Matthias added that feature specifically to make it work faster and more immediately (at some small cost in theoretical quality).

In the case of our plugins, there is one very obvious feature that rules out causal behaviour - normalisation. It's not possible to normalise to a peak level across a whole audio track without having seen the whole audio.

However, even without normalisation the methods are implemented non-causally currently and there are undoubtedly some assumptions in there that would have to be changed or revised if we were to change this (as well as some architectural work in the code, since one reason for writing it this way in the first place was that it is easier to do so). It's not at all unthinkable that we could do this, but it's not totally trivial.

Finally it's quite possible that the code also runs slower than it should do and that there are some simple optimisation opportunities independent of the overall structure of the method. I haven't knowingly written anything to run especially slowly (!) but it's possible there are improvements to be made.

**Comment by cannam** [comment]
> Finally it's quite possible that the code also runs slower than it should do and that there are some simple optimisation opportunities independent of the overall structure of the method. I haven't knowingly written anything to run especially slowly (!) but it's possible there are improvements to be made.

A sanity check for this would simply be to compare the runtime with that of pYin. It has to be longer of course because it runs pYin, but it shouldn't be many times longer. I'd guess the smoothing for the spectral detector is the slowest bit, other than pYin. I would also expect our plugins to have roughly similar runtime to each other, and it should make no difference which output of a given plugin is selected.

So let's test it!

(Oldish Linux laptop, running plugins using `sonic-annotator` at command line against the Szeryng, duration 16.5 sec, WAV format)

```
Time (sec)  Plugin
3.1         Onsets
3.1         Articulation
3.1         Portamento
3.1         Pitch Vibrato
0.6         pYin (Smoothed pitch track) with default parameters
3.0         pYin (Smoothed pitch track) with precise timing enabled
```

So most of the time is in fact going to pYin's precise timing mode! I knew that was slower (the documentation says so!) but I certainly hadn't realised how much of the time it would end up taking and I hadn't previously measured it.

The rationale for using precise timing mode is explained [here](https://github.com/cannam/expressive-means/blob/v0.3.1/src/CoreFeatures.cpp#L404). I believe it should be possible to work around it, with care, and get the same results using the default parameters - precise timing mode just made it easier to get it right without errors in the first place. Something to look at.

**Comment by FrithjofVollmer** [comment]
> In the case of our plugins, there is one very obvious feature that rules out causal behaviour - normalisation. 

> So most of the time is in fact going to pYin's precise timing mode! I knew that was slower (the documentation says so!) but I certainly hadn't realised how much of the time it would end up taking and I hadn't previously measured it.

…impressive! So this means there in fact is a way to significantly speed up processing by switching off normalisation and by implementing a workaround for pYin as described above? How much effort do you think this would involve?

**Comment by cannam** [comment]
> So this means there in fact is a way to significantly speed up processing by switching off normalisation and by implementing a workaround for pYin as described above?

That's not _quite_ right. There are two things going on:

1. Yes, it appears we can make it about 4x quicker by switching to the "imprecise" mode - this will need what I think is a small change to the timing alignment calculation - I'll need to make sure the test cases cover it properly but it doesn't look difficult and I think it shouldn't significantly alter the results. However, this won't change the fact that the results are calculated all at once at the end of the input - they'll arrive quicker but they won't arrive "incrementally".
2. To make the results arrive "incrementally" might be possible, but it would take more than just switching off normalisation. I just mentioned normalisation because it is a very obvious example of a thing that can't be done causally. I don't actually know what else would be needed, but I suspect that e.g. the code that performs multiple passes to identify vibrato elements and associate them with onsets might need a significant amount of work to support incremental generation. Changes of that scale also have the prospect of introducing new bugs.

My feeling is that (1) is totally practical to do for 1.0 and we should do it, but (2) is not a good idea at this point.

**Comment by FrithjofVollmer** [comment]
Cool, yes, let's do this! Would it be possible to involve a tick box to switch back to precise timing if needed? 

Thank you!

**Comment by FrithjofVollmer** [comment]
(This is now implemented and tested within the "pYin" branch; still needs to be merged to "default" and added to the semantic plugin modes [Onsets, Articulation, Pitch Vibrato, Portamento], with the "pYin: precise timing" switch set to "off" by default.)

**Comment by FrithjofVollmer** [comment]
Done by commit [e309ac9](https://github.com/cannam/expressive-means/commit/e309ac9d76bf49040304fd21231fe14ccb8dc778) et al.
