### ISSUE TITLE
Pitch onset detection: another bug?

### ISSUE THREAD

**Issue by FrithjofVollmer** [cannam/expressive-means#28]
There still has to be some minor problem with the logic in pitch detection. Consider the pitch detection curve (green, screenshot: 1988 Brendel_Schubert recording): 

<img width="1512" alt="Screenshot 2023-06-12 at 11 15 29" src="https://github.com/cannam/expressive-means/assets/122092828/bd7d9abe-2695-4cb1-8c2b-9b566979c9b0">

It shows a rise to 6 Cents, then falls to 0.4 Cents. Even though both onset layer have considerable higher "Onset sensitivity: Pitch" thresholds (15 and 9999999 Cents, respectively), an Onset is detected. This particularly seems to be the case in instances where the pitch track is interrupted. Looks to me as if something isn't properly connected here..? 

(--> According to the logic, the function has to exceed the "Onset sensitivity: Pitch" threshold first for at least the duration of the "Minimum onset interval" and then fall below this threshold again to define a new pitch onset)

**Comment by cannam** [comment]
Yep, it looks like there's a logical omission in [the loop here](https://github.com/cannam/expressive-means/blob/default/src/CoreFeatures.cpp#L496). We check the number of hops since the detection function was last below the threshold and assume that that is the same as the number of hops in which the d.f. was above the threshold - but the below threshold test also fails when there is no pitch, so it is not true that a series of hops not below the threshold implies a series of hops above it.

(Also did I see you removed the hard-coded 20ms delay for pitch onsets?)

**Comment by FrithjofVollmer** [comment]
> Also did I see you removed the hard-coded 20ms delay for pitch onsets?

Yes, this was done by commits 4c2b1db and 9de3282 – I think at the end of the day, the idea didn't really pay off (after a number of additional test I found that especially short note duration have been reported too early, entailing significant misinterpretations of onset noise ratios, vibrato elements, and others; so it seemed to be a horse trade really) plus, it makes a use of the Pitch Onset Detection Function a bit unhandy (see my own blackout discussed in https://github.com/cannam/expressive-means/issues/19#issuecomment-1535098691 ....). However, it was worth the try!
